import { ProjectExportData } from "./exportProject";

export function generateReactRouterLayout(data: ProjectExportData): Record<string, string> {
  const { project, brief } = data;
  const projectNameSafe = project.title.replace(/[^a-zA-Z0-9]/g, "");

  const files: Record<string, string> = {};

  // package.json
  files["package.json"] = JSON.stringify({
    name: projectNameSafe.toLowerCase() || "designflow-export",
    version: "1.0.0",
    private: true,
    dependencies: {
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "react-router-dom": "^6.22.0",
      "lucide-react": "^0.344.0"
    },
    scripts: {
      "start": "react-scripts start",
      "build": "react-scripts build"
    }
  }, null, 2);

  // src/App.tsx
  files["src/App.tsx"] = `import React from "react";
import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom";
import { Home } from "./pages/Home";
import { About } from "./pages/About";
import { Contact } from "./pages/Contact";

export default function App() {
  return (
    <Router>
      <div className="min-h-screen flex flex-col bg-gray-50">
        <header className="bg-white shadow-sm">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
            <h1 className="font-bold text-xl">${project.title}</h1>
            <nav className="flex gap-4">
              <Link to="/" className="text-gray-600 hover:text-gray-900">Home</Link>
              <Link to="/about" className="text-gray-600 hover:text-gray-900">About</Link>
              <Link to="/contact" className="text-gray-600 hover:text-gray-900">Contact</Link>
            </nav>
          </div>
        </header>

        <main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/about" element={<About />} />
            <Route path="/contact" element={<Contact />} />
          </Routes>
        </main>
        
        <footer className="bg-white border-t py-6 mt-auto">
          <div className="max-w-7xl mx-auto px-4 text-center text-gray-500 text-sm">
            &copy; {new Date().getFullYear()} ${brief?.companyName || project.title}. All rights reserved.
          </div>
        </footer>
      </div>
    </Router>
  );
}`;

  // src/pages/Home.tsx
  files["src/pages/Home.tsx"] = `import React from "react";

export function Home() {
  return (
    <div className="space-y-6">
      <h2 className="text-3xl font-bold">Welcome to ${project.title}</h2>
      <p className="text-gray-600 max-w-2xl text-lg">
        ${project.description}
      </p>
      
      <div className="mt-8">
        <h3 className="text-xl font-semibold mb-4">Project Overview</h3>
        <div className="bg-white p-6 rounded-lg shadow-sm border">
          <p>This layout was generated by DesignFlow.</p>
        </div>
      </div>
    </div>
  );
}`;

  // src/pages/About.tsx
  files["src/pages/About.tsx"] = `import React from "react";

export function About() {
  return (
    <div className="space-y-6">
      <h2 className="text-3xl font-bold">About ${brief?.companyName || "Us"}</h2>
      ${brief?.companyBackground ? `<p className="text-gray-600 max-w-2xl">${brief.companyBackground}</p>` : `<p className="text-gray-600">No background provided.</p>`}
    </div>
  );
}`;

  // src/pages/Contact.tsx
  files["src/pages/Contact.tsx"] = `import React from "react";

export function Contact() {
  return (
    <div className="space-y-6">
      <h2 className="text-3xl font-bold">Contact ${brief?.contactName || "Us"}</h2>
      <p className="text-gray-600">Get in touch with our team.</p>
    </div>
  );
}`;

  // src/index.tsx
  files["src/index.tsx"] = `import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";

const root = createRoot(document.getElementById("root")!);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`;

  // src/index.css
  files["src/index.css"] = `/* Tailwind CSS would normally be imported here */
body {
  margin: 0;
  font-family: system-ui, -apple-system, sans-serif;
}`;

  return files;
}

